version: '3.8'

services:

  db:
    image: mysql
    container_name: "mysql-container"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adharika11
    ports:
      - "3305:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - mysql-data:/var/lib/mysql
  ecommerce-redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
    redis-data:
    mysql-data: